// frontend/src/pages/DemandaDetalhes.jsx
import React, { useContext, useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { format } from 'date-fns';
import api from '../api';
import { UserContext } from '../App';

const PRIORIDADES = ['crítica', 'alta', 'média', 'baixa'];
const CANAIS_ORIGEM = ['SMAX', 'SEI/CPA', 'E-mail', 'Reunião', 'Teams'];
const DOMINIOS = ['Judicial', 'Administrativo', 'Misto'];

function formatDate(value) {
  if (!value) return 'N/A';
  return format(new Date(value), 'dd/MM/yyyy HH:mm');
}
function formatDateOnly(value) {
  if (!value) return 'N/A';
  return format(new Date(value), 'dd/MM/yyyy');
}
function toDateInput(value) {
  if (!value) return '';
  try { return format(new Date(value), 'yyyy-MM-dd'); } catch { return ''; }
}

function Field({ label, value }) {
  return (
    <div className="detail-field">
      <span>{label}</span>
      <strong>{value || 'N/A'}</strong>
    </div>
  );
}

function labelEvento(tipo, payload) {
  const p = payload || {};
  switch (tipo) {
    case 'criada':                return 'Demanda cadastrada';
    case 'status_alterado':       return `Status: ${p.de} → ${p.para}`;
    case 'coordenadoria_alterada':return `Coordenadoria: ${p.de_nome} → ${p.para_nome}`;
    case 'priorizacao_aprovada':  return 'Priorização aprovada';
    case 'priorizacao_rejeitada': return 'Priorização rejeitada';
    case 'dependencia_cadastrada':return `Dependência cadastrada: ${p.coordenadoria_nome || ''}`;
    case 'dependencia_rejeitada': return `Dependência rejeitada: ${p.coordenadoria_nome || ''}`;
    case 'dependencia_concluida': return `Dependência concluída: ${p.coordenadoria_nome || ''}${p.demanda_filha_id ? ` (Demanda ${p.demanda_filha_id})` : ''}`;
    default:                      return tipo;
  }
}

export default function DemandaDetalhes() {
  const { id } = useParams();
  const navigate = useNavigate();
  const currentUser = useContext(UserContext);

  const [demanda, setDemanda] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  const [editMode, setEditMode] = useState(false);
  const [editForm, setEditForm] = useState({});
  const [saving, setSaving] = useState(false);
  const [saveError, setSaveError] = useState('');

  const [deleteConfirm, setDeleteConfirm] = useState(false);

  const [coordenadorias, setCoordenadorias] = useState([]);
  const [usuarios, setUsuarios] = useState([]);
  const [macroBacklogs, setMacroBacklogs] = useState([]);

  const loadDemanda = () => {
    setLoading(true);
    api.get(`/demandas/${id}`)
      .then(res => setDemanda(res.data))
      .catch(err => setError(err.response?.data?.error || 'Erro ao carregar detalhes.'))
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    loadDemanda();
    api.get('/coordenadorias').then(r => setCoordenadorias(r.data)).catch(console.error);
    api.get('/auth/users').then(r => setUsuarios(r.data)).catch(console.error);
  }, [id]);

  // Carrega os macro_backlogs disponíveis conforme a coordenadoria selecionada no editForm
  useEffect(() => {
    if (!editMode) return;
    if (!editForm.coordenadoria_id) {
      setMacroBacklogs([]);
      return;
    }
    api
      .get(`/coordenadorias/${editForm.coordenadoria_id}/macro-backlogs`)
      .then(r => {
        setMacroBacklogs(r.data);
        setEditForm(prev => {
          if (prev.macro_backlog_id && !r.data.some(m => String(m.id) === String(prev.macro_backlog_id))) {
            return { ...prev, macro_backlog_id: '' };
          }
          return prev;
        });
      })
      .catch(console.error);
  }, [editMode, editForm.coordenadoria_id]);

  // ── Edit helpers ──────────────────────────────────────────────
  const handleEdit = () => {
    setEditForm({
      titulo: demanda.titulo || '',
      descricao: demanda.descricao || '',
      coordenadoria_id: demanda.coordenadoria_id || '',
      macro_backlog_id: demanda.macro_backlog_id || '',
      prioridade: demanda.prioridade || '',
      canal_origem: demanda.canal_origem || '',
      solicitante: demanda.solicitante || '',
      setor_demandante: demanda.setor_demandante || '',
      responsavel_id: demanda.responsavel_id || '',
      prazo: toDateInput(demanda.prazo),
      dominio: demanda.dominio || '',
      previsao_entrega: toDateInput(demanda.previsao_entrega),
      justificativa_priorizacao: '', // campo para novo pedido — começa em branco
      aguarda_areas: demanda.dependencias
        ?.filter(dep => dep.status === 'pendente')
        .map(dep => ({ coordenadoria_id: dep.coordenadoria_id, detalhes: dep.detalhes || '' })) || [],
      solicitar_priorizacao: false,
    });
    setSaveError('');
    setEditMode(true);
  };

  const handleCancel = () => { setEditMode(false); setSaveError(''); };

  const handleChange = (e) => {
    const { name, value, type, checked } = e.target;
    setEditForm(prev => ({ ...prev, [name]: type === 'checkbox' ? checked : value }));
  };

  const handleAreaToggle = (coordenadoria_id) => {
    setEditForm(prev => {
      const exists = prev.aguarda_areas.some(a => a.coordenadoria_id === coordenadoria_id);
      return {
        ...prev,
        aguarda_areas: exists
          ? prev.aguarda_areas.filter(a => a.coordenadoria_id !== coordenadoria_id)
          : [...prev.aguarda_areas, { coordenadoria_id, detalhes: '' }],
      };
    });
  };

  const handleAreaDetalhes = (coordenadoria_id, detalhes) => {
    setEditForm(prev => ({
      ...prev,
      aguarda_areas: prev.aguarda_areas.map(a =>
        a.coordenadoria_id === coordenadoria_id ? { ...a, detalhes } : a
      ),
    }));
  };

  const handleSave = async () => {
    setSaving(true);
    setSaveError('');
    try {
      await api.put(`/demandas/${id}`, { ...editForm, usuario_id: currentUser?.id });
      setEditMode(false);
      loadDemanda();
    } catch (err) {
      setSaveError(err.response?.data?.error || 'Erro ao salvar alterações.');
    } finally {
      setSaving(false);
    }
  };

  // ── Delete ────────────────────────────────────────────────────
  const handleDelete = async () => {
    try {
      await api.delete(`/demandas/${id}`);
      navigate('/');
    } catch (err) {
      setError(err.response?.data?.error || 'Erro ao excluir demanda.');
    }
  };

  // ── Render ────────────────────────────────────────────────────
  if (loading) return <p>Carregando detalhes...</p>;
  if (error) return <div className="form-error">{error}</div>;
  if (!demanda) return null;

  const priorizacaoPendente = !!demanda.flag_priorizacao_solicitada;
  const ultimaDecisaoPrio = demanda.historico_eventos?.find(e =>
    e.tipo === 'priorizacao_aprovada' || e.tipo === 'priorizacao_rejeitada'
  );
  const foiAprovada = !priorizacaoPendente && ultimaDecisaoPrio?.tipo === 'priorizacao_aprovada';
  const podesolicitar = !priorizacaoPendente && !foiAprovada;

  return (
    <div className="detail-page">
      {/* ── Cabeçalho ── */}
      <div className={`detail-header area-card-${demanda.coordenadoria_id}`}>
        <div className="detail-header-meta">
          <span className="detail-eyebrow">Demanda #{demanda.id}</span>
          <span className="detail-eyebrow-sep">•</span>
          <span className="detail-eyebrow">{demanda.coordenadoria_nome}</span>
          {demanda.demanda_mae_id && (
            <>
              <span className="detail-eyebrow-sep">•</span>
              <button
                className="detail-mae-badge"
                onClick={() => navigate(`/demandas/${demanda.demanda_mae_id}`)}
                title={`Ir para a demanda mãe: ${demanda.demanda_mae_titulo}`}
              >
                ↑ Demanda mãe: {demanda.demanda_mae_id} - {demanda.demanda_mae_titulo}
              </button>
            </>
          )}
        </div>

        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: '1rem' }}>
          {editMode ? (
            <input
              name="titulo"
              value={editForm.titulo}
              onChange={handleChange}
              className="edit-input"
              style={{ fontSize: '1.3rem', fontWeight: 700, flex: 1 }}
              required
            />
          ) : (
            <h2 style={{ margin: 0 }}>{demanda.titulo}</h2>
          )}

          <div style={{ display: 'flex', gap: '0.5rem', flexShrink: 0 }}>
            {editMode ? (
              <>
                <button className="btn btn-secondary" onClick={handleCancel} disabled={saving}>Cancelar</button>
                <button className="btn btn-save" onClick={handleSave} disabled={saving}>
                  {saving ? 'Salvando...' : '✓ Salvar'}
                </button>
              </>
            ) : (
              <>
                {deleteConfirm ? (
                  <>
                    <span style={{ fontSize: '0.85rem', color: 'var(--text-muted)', alignSelf: 'center' }}>Confirmar exclusão?</span>
                    <button className="btn btn-secondary" onClick={() => setDeleteConfirm(false)}>Não</button>
                    <button className="btn btn-danger" onClick={handleDelete}>Sim, excluir</button>
                  </>
                ) : (
                  <>
                    <button className="btn btn-danger-outline" onClick={() => setDeleteConfirm(true)}>Excluir</button>
                    <button className="btn btn-secondary" onClick={handleEdit}>✎ Editar</button>
                  </>
                )}
              </>
            )}
          </div>
        </div>

        <div className="detail-badges" style={{ marginTop: '0.75rem' }}>
          <span className={`badge badge-priority-${demanda.prioridade.toLowerCase().replace('é', 'e')}`}>
            {demanda.prioridade}
          </span>
          <span className={`badge badge-status-${demanda.status.toLowerCase().replace(' ', '-')}`}>
            {demanda.status}
          </span>
        </div>
      </div>

      {saveError && <div className="form-error" style={{ marginTop: '1rem' }}>{saveError}</div>}

      {/* ── Descrição ── */}
      <section className="detail-section">
        <h3>Descrição</h3>
        {editMode ? (
          <textarea name="descricao" rows={4} value={editForm.descricao} onChange={handleChange} className="edit-input" style={{ width: '100%' }} />
        ) : (
          <p className="detail-description">{demanda.descricao || 'Sem descrição.'}</p>
        )}
      </section>

      {/* ── Origem e Contexto ── */}
      <section className="detail-section">
        <h3>Origem e Contexto</h3>
        {editMode ? (
          <div className="detail-edit-grid">
            <div className="detail-edit-field">
              <label>Canal de Origem</label>
              <select name="canal_origem" value={editForm.canal_origem} onChange={handleChange} className="edit-input">
                <option value="">Selecione...</option>
                {CANAIS_ORIGEM.map(c => <option key={c} value={c}>{c}</option>)}
              </select>
            </div>
            <div className="detail-edit-field">
              <label>Domínio</label>
              <select name="dominio" value={editForm.dominio} onChange={handleChange} className="edit-input">
                <option value="">Selecione...</option>
                {DOMINIOS.map(d => <option key={d} value={d}>{d}</option>)}
              </select>
            </div>
            <div className="detail-edit-field">
              <label>Solicitante</label>
              <input name="solicitante" value={editForm.solicitante} onChange={handleChange} className="edit-input" />
            </div>
            <div className="detail-edit-field">
              <label>Setor Demandante</label>
              <input name="setor_demandante" value={editForm.setor_demandante} onChange={handleChange} className="edit-input" />
            </div>
            <div className="detail-edit-field">
              <label>Responsável</label>
              <select name="responsavel_id" value={editForm.responsavel_id} onChange={handleChange} className="edit-input">
                <option value="">Selecione...</option>
                {usuarios.map(u => <option key={u.id} value={u.id}>{u.nome}</option>)}
              </select>
            </div>
            <div className="detail-edit-field">
              <label>Prazo</label>
              <input type="date" name="prazo" value={editForm.prazo} onChange={handleChange} className="edit-input" />
            </div>
            <div className="detail-edit-field">
              <label>Previsão de Entrega</label>
              <input type="date" name="previsao_entrega" value={editForm.previsao_entrega} onChange={handleChange} className="edit-input" />
            </div>
          </div>
        ) : (
          <div className="detail-grid">
            <Field label="Canal de Origem" value={demanda.canal_origem} />
            <Field label="Domínio" value={demanda.dominio} />
            <Field label="Solicitante" value={demanda.solicitante} />
            <Field label="Setor Demandante" value={demanda.setor_demandante} />
            <Field label="Responsável" value={demanda.responsavel_nome} />
            <Field label="Prazo" value={formatDateOnly(demanda.prazo)} />
            <Field label="Previsão de Entrega" value={formatDateOnly(demanda.previsao_entrega)} />
          </div>
        )}
      </section>

      {/* ── Dados da Demanda ── */}
      <section className="detail-section">
        <h3>Dados da Demanda</h3>
        {editMode ? (
          <div className="detail-edit-grid">
            <div className="detail-edit-field">
              <label>Coordenadoria</label>
              <select name="coordenadoria_id" value={editForm.coordenadoria_id} onChange={handleChange} className="edit-input">
                <option value="">Selecione...</option>
                {coordenadorias.map(c => <option key={c.id} value={c.id}>{c.nome}</option>)}
              </select>
            </div>
            <div className="detail-edit-field">
              <label>Macro Backlog</label>
              <select
                name="macro_backlog_id"
                value={editForm.macro_backlog_id}
                onChange={handleChange}
                className="edit-input"
                disabled={!editForm.coordenadoria_id}
              >
                <option value="">
                  {editForm.coordenadoria_id ? 'Selecione...' : 'Selecione a coordenadoria antes'}
                </option>
                {macroBacklogs.map(m => <option key={m.id} value={m.id}>{m.nome}</option>)}
              </select>
            </div>
            <div className="detail-edit-field">
              <label>Criticidade</label>
              <select name="prioridade" value={editForm.prioridade} onChange={handleChange} className="edit-input">
                <option value="">Selecione...</option>
                {PRIORIDADES.map(p => <option key={p} value={p}>{p.charAt(0).toUpperCase() + p.slice(1)}</option>)}
              </select>
            </div>
          </div>
        ) : (
          <div className="detail-grid">
            <Field label="ID" value={demanda.id} />
            <Field label="Coordenadoria" value={demanda.coordenadoria_nome} />
            <Field label="Macro Backlog" value={demanda.macro_backlog_nome} />
            <Field label="Criador" value={demanda.criador_nome} />
            <Field label="Fixada" value={demanda.pinned ? 'Sim' : 'Não'} />
            <Field label="Priorização solicitada" value={demanda.flag_priorizacao_solicitada ? 'Sim' : 'Não'} />
            <Field label="Criada em" value={formatDate(demanda.created_at)} />
            <Field label="Concluída em" value={formatDate(demanda.concluded_at)} />
          </div>
        )}
      </section>

      {/* ── Dependências ── */}
      <section className="detail-section">
        <h3>Dependências</h3>
        {editMode ? (
          <div className="dependencias-list" style={{ marginTop: '0.5rem' }}>
            {coordenadorias.map(c => {
              const selected = editForm.aguarda_areas.some(a => a.coordenadoria_id === c.id);
              return (
                <div key={c.id} className="dep-item dep-item-details">
                  <label className="dep-check-row">
                    <input type="checkbox" checked={selected} onChange={() => handleAreaToggle(c.id)} />
                    <span>{c.nome}</span>
                  </label>
                  {selected && (
                    <textarea
                      rows={2}
                      placeholder="Detalhe o que esta dependência precisa resolver..."
                      value={editForm.aguarda_areas.find(a => a.coordenadoria_id === c.id)?.detalhes || ''}
                      onChange={(e) => handleAreaDetalhes(c.id, e.target.value)}
                      className="edit-input"
                    />
                  )}
                </div>
              );
            })}
          </div>
        ) : (
          demanda.dependencias?.length ? (
            <div className="detail-dependencies">
              {demanda.dependencias.map(dep => (
                <div
                  key={dep.id}
                  className={`detail-dependency area-card-${dep.coordenadoria_id}${dep.demanda_filha_id && dep.status === 'concluida' ? ' detail-dependency-filha' : ''}`}
                  onClick={dep.demanda_filha_id && dep.status === 'concluida' ? () => navigate(`/demandas/${dep.demanda_filha_id}`) : undefined}
                  style={dep.demanda_filha_id && dep.status === 'concluida' ? { cursor: 'pointer' } : undefined}
                >
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <strong>{dep.coordenadoria_nome}</strong>
                    <span style={{ fontSize: '0.72rem', opacity: 0.6 }}>{formatDate(dep.created_at)}</span>
                  </div>
                  {dep.status !== 'concluida' && (
                    <p style={{ margin: '0.2rem 0 0' }}>{dep.detalhes || 'Sem detalhes informados.'}</p>
                  )}
                  {dep.demanda_filha_id && (
                    <div
                      className="dep-filha-link"
                      onClick={dep.status !== 'concluida' ? (e) => { e.stopPropagation(); navigate(`/demandas/${dep.demanda_filha_id}`); } : undefined}
                      style={dep.status !== 'concluida' ? { cursor: 'pointer' } : undefined}
                    >
                      <span className={`badge badge-status-${(dep.demanda_filha_status || '').toLowerCase().replace(' ', '-')}`} style={{ fontSize: '0.7rem' }}>
                        {dep.demanda_filha_status}
                      </span>
                      <span>Demanda {dep.demanda_filha_id} — {dep.demanda_filha_titulo}</span>
                    </div>
                  )}
                </div>
              ))}
            </div>
          ) : (
            <p className="detail-muted">Sem dependências cadastradas.</p>
          )
        )}
      </section>

      {/* ── Pedido de Priorização ── */}
      <section className="detail-section">
        <h3>Pedido de Priorização</h3>

        {editMode ? (
          <>
            {priorizacaoPendente && (
              <p style={{ color: 'var(--warning)', fontSize: '0.9rem' }}>
                ⏳ Já existe um pedido em análise pelo diretor.
              </p>
            )}

            {foiAprovada && (
              <p style={{ color: 'var(--success)', fontSize: '0.9rem' }}>
                ✓ A priorização desta demanda já foi aprovada.
              </p>
            )}

            {podesolicitar && (
              <>
                <div className="form-group-checkbox">
                  <label className="checkbox-label">
                    <input
                      type="checkbox"
                      name="solicitar_priorizacao"
                      checked={editForm.solicitar_priorizacao}
                      onChange={handleChange}
                    />
                    <span className="checkbox-text">
                      <strong>Solicitar Priorização ao Diretor</strong>
                    </span>
                  </label>
                </div>
                {editForm.solicitar_priorizacao && (
                  <div className="detail-edit-field" style={{ marginTop: '0.75rem' }}>
                    <label>Justificativa</label>
                    <textarea
                      name="justificativa_priorizacao"
                      rows={3}
                      placeholder="Descreva o motivo pelo qual esta demanda deve ser priorizada..."
                      value={editForm.justificativa_priorizacao}
                      onChange={handleChange}
                      className="edit-input"
                    />
                  </div>
                )}
              </>
            )}
          </>
        ) : (
          <>
            {priorizacaoPendente ? (
              <>
                <p style={{ color: 'var(--warning)', fontSize: '0.9rem', marginBottom: '0.75rem' }}>
                  ⏳ Pedido em análise pelo diretor.
                </p>
                {demanda.justificativa_priorizacao && (
                  <div className="detail-field detail-field-full">
                    <span>Justificativa</span>
                    <p className="detail-description">{demanda.justificativa_priorizacao}</p>
                  </div>
                )}
              </>
            ) : foiAprovada ? (
              <p style={{ color: 'var(--success)', fontSize: '0.9rem' }}>
                ✓ Priorização aprovada.
              </p>
            ) : (
              <p className="detail-muted">Nenhum pedido ativo.</p>
            )}
          </>
        )}
      </section>

      {/* ── Histórico de Eventos ── */}
      <section className="detail-section">
        <h3>Histórico de Eventos</h3>
        {demanda.historico_eventos?.length ? (
          <div className="detail-history">
            {demanda.historico_eventos.map(ev => (
              <div key={ev.id} className="detail-history-item">
                <strong>{labelEvento(ev.tipo, ev.payload)}</strong>
                <span>{ev.usuario_nome || '—'} em {formatDate(ev.created_at)}</span>
              </div>
            ))}
          </div>
        ) : (
          <p className="detail-muted">Sem eventos registrados.</p>
        )}
      </section>
    </div>
  );
}

// frontend/src/app/pages/demanda-detalhes/demanda-detalhes.component.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule, DatePipe } from '@angular/common';
import { RouterModule, ActivatedRoute, Router } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../core/services/api.service';
import { UserService } from '../../core/services/user.service';

interface Dependencia {
  id: number;
  demanda_id: number;
  coordenadoria_id: number;
  coordenadoria_nome: string;
  status: string;
  detalhes: string;
  demanda_filha_id: number;
}

interface HistoricoEvento {
  id: number;
  tipo: string;
  usuario_nome: string;
  payload: any;
  created_at: string;
}

interface Demanda {
  id: number;
  titulo: string;
  descricao: string;
  coordenadoria_id: number;
  coordenadoria_nome: string;
  macro_backlog_id: number;
  macro_backlog_nome: string;
  prioridade: string;
  status: string;
  criador_id: number;
  criador_nome: string;
  responsavel_id: number;
  responsavel_nome: string;
  prazo: string;
  dominio: string;
  previsao_entrega: string;
  canal_origem: string;
  solicitante: string;
  setor_demandante: string;
  pinned: boolean;
  pin_order: number;
  flag_priorizacao_solicitada: boolean;
  created_at: string;
  concluded_at: string;
  dependencias: Dependencia[];
  historico: HistoricoEvento[];
  demanda_mae_id?: number;
  demanda_mae_titulo?: string;
}

interface Coordenadoria { id: number; nome: string; }
interface MacroBacklog { id: number; nome: string; }
interface Usuario { id: number; nome: string; role: string; }

@Component({
  selector: 'app-demanda-detalhes',
  standalone: true,
  imports: [CommonModule, RouterModule, FormsModule, DatePipe],
  templateUrl: './demanda-detalhes.component.html',
  providers: [DatePipe]
})
export class DemandaDetalhesComponent implements OnInit {
  private api = inject(ApiService);
  private route = inject(ActivatedRoute);
  private router = inject(Router);
  userService = inject(UserService);

  demanda = signal<Demanda | null>(null);
  loading = signal(true);
  editMode = signal(false);
  saving = signal(false);
  error = signal('');

  coordenadorias = signal<Coordenadoria[]>([]);
  macroBacklogs = signal<MacroBacklog[]>([]);
  usuarios = signal<Usuario[]>([]);

  editForm: Partial<Demanda> = {};

  readonly PRIORIDADES = ['crítica', 'alta', 'média', 'baixa'];
  readonly STATUS = ['pendente', 'em andamento', 'em revisão', 'concluída', 'cancelada', 'suspensa'];
  readonly CANAIS = ['SMAX', 'SEI/CPA', 'E-mail', 'Reunião', 'Teams'];
  readonly DOMINIOS = ['Judicial', 'Administrativo', 'Misto'];

  ngOnInit(): void {
    const id = this.route.snapshot.paramMap.get('id');
    this.api.get<Demanda>(`/demandas/${id}`).subscribe({
      next: (d) => { this.demanda.set(d); this.loading.set(false); },
      error: () => { this.error.set('Demanda não encontrada.'); this.loading.set(false); }
    });
    this.api.get<Coordenadoria[]>('/coordenadorias').subscribe({ next: c => this.coordenadorias.set(c) });
    this.api.get<MacroBacklog[]>('/macro-backlogs').subscribe({ next: m => this.macroBacklogs.set(m) });
    this.api.get<Usuario[]>('/auth/users').subscribe({ next: u => this.usuarios.set(u) });
  }

  startEdit(): void {
    const d = this.demanda();
    if (!d) return;
    this.editForm = { ...d };
    this.editMode.set(true);
  }

  cancelEdit(): void {
    this.editMode.set(false);
    this.error.set('');
  }

  saveEdit(): void {
    const d = this.demanda();
    if (!d) return;
    this.saving.set(true);
    const body = { ...this.editForm, usuario_id: this.userService.currentUser()?.id };
    this.api.put<Demanda>(`/demandas/${d.id}`, body).subscribe({
      next: (updated) => {
        this.demanda.set(updated);
        this.editMode.set(false);
        this.saving.set(false);
      },
      error: (err) => {
        this.error.set(err?.error?.message ?? 'Erro ao salvar.');
        this.saving.set(false);
      }
    });
  }

  deleteDemanda(): void {
    const d = this.demanda();
    if (!d) return;
    if (!confirm(`Excluir demanda "${d.titulo}"?`)) return;
    this.api.delete<void>(`/demandas/${d.id}`).subscribe({
      next: () => this.router.navigate(['/']),
      error: () => this.error.set('Erro ao excluir.')
    });
  }

  solicitarPriorizacao(): void {
    const d = this.demanda();
    if (!d) return;
    const body = {
      solicitar_priorizacao: true,
      usuario_id: this.userService.currentUser()?.id
    };
    this.api.put<Demanda>(`/demandas/${d.id}`, body).subscribe({
      next: (updated) => this.demanda.set(updated)
    });
  }

  labelEvento(evento: HistoricoEvento): string {
    const p = evento.payload ?? {};
    switch (evento.tipo) {
      case 'criada': return 'Demanda cadastrada';
      case 'status_alterado': return `Status: ${p.de} → ${p.para}`;
      case 'coordenadoria_alterada': return `Coordenadoria: ${p.de_nome} → ${p.para_nome}`;
      case 'priorizacao_aprovada': return 'Priorização aprovada';
      case 'priorizacao_rejeitada': return 'Priorização rejeitada';
      case 'dependencia_cadastrada': return `Dependência cadastrada: ${p.coordenadoria_nome}`;
      case 'dependencia_concluida': return `Dependência concluída: ${p.coordenadoria_nome}`;
      case 'dependencia_rejeitada': return `Dependência rejeitada: ${p.coordenadoria_nome}`;
      default: return evento.tipo;
    }
  }

  priorityClass(p: string): string {
    const map: Record<string, string> = {
      'crítica': 'badge-priority-crítica',
      'alta': 'badge-priority-alta',
      'média': 'badge-priority-media',
      'baixa': 'badge-priority-baixa'
    };
    return map[p] ?? '';
  }

  statusClass(s: string): string {
    const map: Record<string, string> = {
      'pendente': 'badge-status-pendente',
      'em andamento': 'badge-status-em-andamento',
      'concluída': 'badge-status-concluída',
      'cancelada': 'badge-status-cancelada',
      'suspensa': 'badge-status-suspensa'
    };
    return map[s] ?? '';
  }

  depStatusClass(s: string): string {
    if (s === 'concluida') return 'badge-status-concluída';
    if (s === 'rejeitada') return 'badge-status-cancelada';
    return 'badge-status-pendente';
  }

  navigateToMae(): void {
    const d = this.demanda();
    if (d?.demanda_mae_id) this.router.navigate(['/demandas', d.demanda_mae_id]);
  }
}

<div *ngIf="loading()" style="color:var(--text-muted);padding:2rem">Carregando...</div>

<div *ngIf="error() && !loading()" class="form-error">{{ error() }}</div>

<div *ngIf="demanda() && !loading()" class="detail-page">
  <!-- Back link -->
  <button class="detail-back-link" routerLink="/">
    <span class="detail-back-arrow">←</span> Voltar às demandas
  </button>

  <!-- Header -->
  <div class="detail-header">
    <div class="detail-header-meta">
      <span class="detail-eyebrow">#{{ demanda()!.id }}</span>
      <span class="detail-eyebrow-sep">·</span>
      <span class="detail-eyebrow">{{ demanda()!.coordenadoria_nome }}</span>
      <span *ngIf="demanda()!.demanda_mae_id" class="detail-eyebrow-sep">·</span>
      <button *ngIf="demanda()!.demanda_mae_id" class="detail-mae-badge" (click)="navigateToMae()">
        ↑ Demanda mãe #{{ demanda()!.demanda_mae_id }}
      </button>
    </div>
    <h2>{{ demanda()!.titulo }}</h2>
    <div class="detail-badges">
      <span class="badge" [class]="priorityClass(demanda()!.prioridade)">{{ demanda()!.prioridade }}</span>
      <span class="badge" [class]="statusClass(demanda()!.status)">{{ demanda()!.status }}</span>
      <span *ngIf="demanda()!.flag_priorizacao_solicitada" class="badge" style="background:rgba(245,158,11,0.1);color:var(--warning);border:1px solid var(--warning)">
        Priorização solicitada
      </span>
    </div>
    <div style="display:flex;gap:0.5rem;flex-wrap:wrap;margin-top:0.5rem">
      <button *ngIf="!editMode()" class="btn btn-primary" (click)="startEdit()">Editar</button>
      <button *ngIf="!editMode() && !demanda()!.flag_priorizacao_solicitada" class="btn btn-warning" (click)="solicitarPriorizacao()">
        Solicitar Priorização
      </button>
      <button *ngIf="!editMode()" class="btn btn-danger-outline" (click)="deleteDemanda()">Excluir</button>
    </div>
  </div>

  <!-- Edit mode -->
  <div *ngIf="editMode()" class="detail-section">
    <h3>Editar Demanda</h3>
    <div *ngIf="error()" class="form-error" style="margin-bottom:1rem">{{ error() }}</div>
    <div class="detail-edit-grid">
      <div class="detail-edit-field detail-edit-field-full">
        <label>Título</label>
        <input class="edit-input" [(ngModel)]="editForm.titulo" />
      </div>
      <div class="detail-edit-field detail-edit-field-full">
        <label>Descrição</label>
        <textarea class="edit-input" rows="4" [(ngModel)]="editForm.descricao"></textarea>
      </div>
      <div class="detail-edit-field">
        <label>Coordenadoria</label>
        <select class="edit-input" [(ngModel)]="editForm.coordenadoria_id">
          <option *ngFor="let c of coordenadorias()" [value]="c.id">{{ c.nome }}</option>
        </select>
      </div>
      <div class="detail-edit-field">
        <label>Macro Backlog</label>
        <select class="edit-input" [(ngModel)]="editForm.macro_backlog_id">
          <option *ngFor="let m of macroBacklogs()" [value]="m.id">{{ m.nome }}</option>
        </select>
      </div>
      <div class="detail-edit-field">
        <label>Prioridade</label>
        <select class="edit-input" [(ngModel)]="editForm.prioridade">
          <option *ngFor="let p of PRIORIDADES" [value]="p">{{ p }}</option>
        </select>
      </div>
      <div class="detail-edit-field">
        <label>Status</label>
        <select class="edit-input" [(ngModel)]="editForm.status">
          <option *ngFor="let s of STATUS" [value]="s">{{ s }}</option>
        </select>
      </div>
      <div class="detail-edit-field">
        <label>Responsável</label>
        <select class="edit-input" [(ngModel)]="editForm.responsavel_id">
          <option *ngFor="let u of usuarios()" [value]="u.id">{{ u.nome }}</option>
        </select>
      </div>
      <div class="detail-edit-field">
        <label>Canal de Origem</label>
        <select class="edit-input" [(ngModel)]="editForm.canal_origem">
          <option *ngFor="let c of CANAIS" [value]="c">{{ c }}</option>
        </select>
      </div>
      <div class="detail-edit-field">
        <label>Domínio</label>
        <select class="edit-input" [(ngModel)]="editForm.dominio">
          <option *ngFor="let d of DOMINIOS" [value]="d">{{ d }}</option>
        </select>
      </div>
      <div class="detail-edit-field">
        <label>Solicitante</label>
        <input class="edit-input" [(ngModel)]="editForm.solicitante" />
      </div>
      <div class="detail-edit-field">
        <label>Setor Demandante</label>
        <input class="edit-input" [(ngModel)]="editForm.setor_demandante" />
      </div>
      <div class="detail-edit-field">
        <label>Prazo</label>
        <input type="date" class="edit-input" [(ngModel)]="editForm.prazo" />
      </div>
      <div class="detail-edit-field">
        <label>Previsão de Entrega</label>
        <input type="date" class="edit-input" [(ngModel)]="editForm.previsao_entrega" />
      </div>
    </div>
    <div style="display:flex;gap:0.5rem;margin-top:1.5rem">
      <button class="btn btn-save" [disabled]="saving()" (click)="saveEdit()">
        {{ saving() ? 'Salvando...' : 'Salvar' }}
      </button>
      <button class="btn btn-secondary" (click)="cancelEdit()">Cancelar</button>
    </div>
  </div>

  <!-- Description -->
  <div *ngIf="!editMode()" class="detail-section">
    <h3>Descrição</h3>
    <p class="detail-description">{{ demanda()!.descricao || 'Sem descrição.' }}</p>
  </div>

  <!-- Details grid -->
  <div *ngIf="!editMode()" class="detail-section">
    <h3>Informações</h3>
    <div class="detail-grid">
      <div class="detail-field">
        <span>Coordenadoria</span>
        <strong>{{ demanda()!.coordenadoria_nome }}</strong>
      </div>
      <div class="detail-field">
        <span>Macro Backlog</span>
        <strong>{{ demanda()!.macro_backlog_nome }}</strong>
      </div>
      <div class="detail-field">
        <span>Criador</span>
        <strong>{{ demanda()!.criador_nome }}</strong>
      </div>
      <div class="detail-field">
        <span>Responsável</span>
        <strong>{{ demanda()!.responsavel_nome }}</strong>
      </div>
      <div class="detail-field">
        <span>Canal de Origem</span>
        <strong>{{ demanda()!.canal_origem || '—' }}</strong>
      </div>
      <div class="detail-field">
        <span>Domínio</span>
        <strong>{{ demanda()!.dominio || '—' }}</strong>
      </div>
      <div class="detail-field">
        <span>Solicitante</span>
        <strong>{{ demanda()!.solicitante || '—' }}</strong>
      </div>
      <div class="detail-field">
        <span>Setor Demandante</span>
        <strong>{{ demanda()!.setor_demandante || '—' }}</strong>
      </div>
      <div class="detail-field">
        <span>Prazo</span>
        <strong>{{ demanda()!.prazo ? (demanda()!.prazo | date:'dd/MM/yyyy') : '—' }}</strong>
      </div>
      <div class="detail-field">
        <span>Previsão de Entrega</span>
        <strong>{{ demanda()!.previsao_entrega ? (demanda()!.previsao_entrega | date:'dd/MM/yyyy') : '—' }}</strong>
      </div>
      <div class="detail-field">
        <span>Criada em</span>
        <strong>{{ demanda()!.created_at | date:'dd/MM/yyyy HH:mm' }}</strong>
      </div>
      <div *ngIf="demanda()!.concluded_at" class="detail-field">
        <span>Concluída em</span>
        <strong>{{ demanda()!.concluded_at | date:'dd/MM/yyyy HH:mm' }}</strong>
      </div>
    </div>
  </div>

  <!-- Dependencies -->
  <div class="detail-section">
    <h3>Dependências ({{ demanda()!.dependencias.length }})</h3>
    <div *ngIf="demanda()!.dependencias.length === 0" class="detail-muted">Sem dependências.</div>
    <div class="detail-dependencies">
      <div *ngFor="let dep of demanda()!.dependencias" class="detail-dependency">
        <div style="display:flex;align-items:center;justify-content:space-between;gap:0.5rem">
          <strong>{{ dep.coordenadoria_nome }}</strong>
          <span class="badge" [class]="depStatusClass(dep.status)">{{ dep.status }}</span>
        </div>
        <p *ngIf="dep.detalhes">{{ dep.detalhes }}</p>
        <div *ngIf="dep.demanda_filha_id" class="dep-filha-link" style="cursor:pointer" [routerLink]="['/demandas', dep.demanda_filha_id]">
          ↳ Demanda filha #{{ dep.demanda_filha_id }}
        </div>
      </div>
    </div>
  </div>

  <!-- History -->
  <div class="detail-section">
    <h3>Histórico ({{ demanda()!.historico.length }})</h3>
    <div *ngIf="demanda()!.historico.length === 0" class="detail-muted">Sem histórico.</div>
    <div class="detail-history">
      <div *ngFor="let ev of demanda()!.historico" class="detail-history-item">
        <strong>{{ labelEvento(ev) }}</strong>
        <div style="text-align:right">
          <span class="detail-muted">{{ ev.usuario_nome }}</span><br>
          <span class="detail-muted" style="font-size:0.8rem">{{ ev.created_at | date:'dd/MM/yyyy HH:mm' }}</span>
        </div>
      </div>
    </div>
  </div>
</div>
