// frontend/src/app/pages/dependencias/dependencias.component.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule, DatePipe } from '@angular/common';
import { RouterModule } from '@angular/router';
import { ApiService } from '../../core/services/api.service';
import { UserService } from '../../core/services/user.service';

interface DepItem {
  id: number;
  demanda_id: number;
  demanda_titulo: string;
  coordenadoria_id: number;
  coordenadoria_nome: string;
  status: string;
  detalhes: string;
  demanda_filha_id: number | null;
  prioridade?: string;
  responsavel_nome?: string;
  created_at?: string;
}

interface DepGrupo {
  coordenadoria_id: number;
  coordenadoria_nome: string;
  dependencias: DepItem[];
}

@Component({
  selector: 'app-dependencias',
  standalone: true,
  imports: [CommonModule, RouterModule, DatePipe],
  templateUrl: './dependencias.component.html',
  providers: [DatePipe]
})
export class DependenciasComponent implements OnInit {
  private api = inject(ApiService);
  userService = inject(UserService);

  grupos = signal<DepGrupo[]>([]);
  loading = signal(true);
  error = signal('');
  processing = signal<Set<number>>(new Set());

  ngOnInit(): void {
    this.load();
  }

  load(): void {
    this.loading.set(true);
    this.api.get<DepGrupo[]>('/dependencias').subscribe({
      next: (data) => { this.grupos.set(data); this.loading.set(false); },
      error: () => { this.error.set('Erro ao carregar dependências.'); this.loading.set(false); }
    });
  }

  get pendingGrupos(): DepGrupo[] {
    return this.grupos()
      .map(g => ({ ...g, dependencias: g.dependencias.filter(d => d.status === 'pendente') }))
      .filter(g => g.dependencias.length > 0);
  }

  concluir(dep: DepItem): void {
    const uid = this.userService.currentUser()?.id;
    this.processing.update(s => { s.add(dep.id); return new Set(s); });
    this.api.post<void>(`/dependencias/${dep.id}/concluir`, { usuario_id: uid }).subscribe({
      next: () => { this.processing.update(s => { s.delete(dep.id); return new Set(s); }); this.load(); },
      error: () => { this.processing.update(s => { s.delete(dep.id); return new Set(s); }); }
    });
  }

  rejeitar(dep: DepItem): void {
    const uid = this.userService.currentUser()?.id;
    this.processing.update(s => { s.add(dep.id); return new Set(s); });
    this.api.post<void>(`/dependencias/${dep.id}/rejeitar`, { usuario_id: uid }).subscribe({
      next: () => { this.processing.update(s => { s.delete(dep.id); return new Set(s); }); this.load(); },
      error: () => { this.processing.update(s => { s.delete(dep.id); return new Set(s); }); }
    });
  }

  isProcessing(id: number): boolean {
    return this.processing().has(id);
  }

  areaHeaderClass(id: number): string {
    if (id <= 3) return `area-header-${id}`;
    return '';
  }

  areaDotClass(id: number): string {
    if (id <= 3) return `area-dot-${id}`;
    return '';
  }

  priorityClass(p: string): string {
    const map: Record<string, string> = {
      'crítica': 'badge-priority-crítica',
      'alta': 'badge-priority-alta',
      'média': 'badge-priority-media',
      'baixa': 'badge-priority-baixa'
    };
    return map[p] ?? '';
  }
}

<div class="dependencias-page">
  <h1 class="dep-page-title">Dependências</h1>
  <p class="dep-page-subtitle">Dependências pendentes de resposta por área</p>

  <div *ngIf="loading()" style="color:var(--text-muted)">Carregando...</div>
  <div *ngIf="error()" class="form-error">{{ error() }}</div>

  <div *ngIf="!loading() && pendingGrupos.length === 0" class="dep-empty">
    <span>✅</span>
    Nenhuma dependência pendente.
  </div>

  <div *ngIf="!loading()" class="dep-grupos">
    <div *ngFor="let grupo of pendingGrupos" class="dep-grupo">
      <!-- Group header -->
      <div class="dep-grupo-header" [class]="areaHeaderClass(grupo.coordenadoria_id)">
        <span class="area-dot" [class]="areaDotClass(grupo.coordenadoria_id)"></span>
        <h3><strong>{{ grupo.coordenadoria_nome }}</strong></h3>
        <span class="dep-count">{{ grupo.dependencias.length }}</span>
      </div>

      <!-- Dependency cards -->
      <div class="dep-grupo-list">
        <div *ngFor="let dep of grupo.dependencias" class="dep-card">
          <div class="dep-card-main">
            <div class="dep-card-title-row">
              <div class="dep-card-title-group">
                <span class="demand-id-badge">{{ dep.demanda_id }}</span>
                <span class="dep-card-titulo">{{ dep.demanda_titulo }}</span>
              </div>
              <div class="dep-card-badges">
                <span *ngIf="dep.prioridade" class="badge" [class]="priorityClass(dep.prioridade)">{{ dep.prioridade }}</span>
              </div>
            </div>

            <div class="dep-card-meta">
              <span *ngIf="dep.responsavel_nome" class="dep-card-meta-item">
                <span class="dep-card-meta-label">Resp.: </span>{{ dep.responsavel_nome }}
              </span>
              <span *ngIf="dep.created_at" class="dep-card-meta-item">
                <span class="dep-card-meta-label">Criada: </span>{{ dep.created_at | date:'dd/MM/yyyy' }}
              </span>
            </div>

            <p *ngIf="dep.detalhes" class="dep-card-detalhes">{{ dep.detalhes }}</p>

            <div *ngIf="dep.demanda_filha_id" class="dep-card-filha" [routerLink]="['/demandas', dep.demanda_filha_id]">
              ↳ Demanda filha {{ dep.demanda_filha_id }}
            </div>
          </div>

          <div class="dep-card-footer">
            <a class="dep-btn-link" [routerLink]="['/demandas', dep.demanda_id]">Ver demanda →</a>
            <div class="dep-card-actions">
              <button
                *ngIf="!dep.demanda_filha_id"
                class="dep-action-btn dep-action-filha"
                [routerLink]="['/nova-demanda']"
                [queryParams]="{dependencia: dep.id}"
                [disabled]="isProcessing(dep.id)">
                + Demanda filha
              </button>
              <button
                class="dep-action-btn dep-action-concluir"
                [disabled]="isProcessing(dep.id)"
                (click)="concluir(dep)">
                {{ isProcessing(dep.id) ? '...' : 'Concluir' }}
              </button>
              <button
                class="dep-action-btn dep-action-rejeitar"
                [disabled]="isProcessing(dep.id)"
                (click)="rejeitar(dep)">
                {{ isProcessing(dep.id) ? '...' : 'Rejeitar' }}
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

// frontend/src/pages/Dependencias.jsx
import React, { useState, useEffect, useContext } from 'react';
import { useNavigate } from 'react-router-dom';
import { format } from 'date-fns';
import api from '../api';
import PinIcon from '../components/PinIcon';
import { UserContext } from '../App';

const TRUNCATE_LEN = 90;
function truncate(text) {
  if (!text) return null;
  return text.length > TRUNCATE_LEN ? text.slice(0, TRUNCATE_LEN).trimEnd() + '…' : text;
}

function formatDateShort(value) {
  if (!value) return '';
  try { return format(new Date(value), 'dd/MM/yyyy'); } catch { return ''; }
}

const PRIORIDADE_LABEL = {
  'crítica': { label: 'Crítica', cls: 'badge-priority-crítica' },
  'alta':    { label: 'Alta',    cls: 'badge-priority-alta' },
  'média':   { label: 'Média',   cls: 'badge-priority-media' },
  'baixa':   { label: 'Baixa',   cls: 'badge-priority-baixa' },
};

const STATUS_LABEL = {
  'pendente':     'badge-status-pendente',
  'em andamento': 'badge-status-em-andamento',
  'concluída':    'badge-status-concluída',
  'suspensa':     'badge-status-suspensa',
  'cancelada':    'badge-status-cancelada',
};

export default function Dependencias() {
  const navigate = useNavigate();
  const currentUser = useContext(UserContext);

  const [grupos, setGrupos] = useState([]);
  const [loading, setLoading] = useState(true);
  const [actionLoading, setActionLoading] = useState(null); // dependencia_id em ação
  const [actionError, setActionError] = useState('');

  const carregarDependencias = () => {
    setLoading(true);
    api.get('/dependencias')
      .then(r => setGrupos(r.data))
      .catch(console.error)
      .finally(() => setLoading(false));
  };

  useEffect(() => { carregarDependencias(); }, []);

  const podeAgir = (coordenadoria_id) =>
    currentUser?.role === 'admin' ||
    Number(currentUser?.coordenadoria_id) === Number(coordenadoria_id);

  const handleRejeitar = async (dep) => {
    if (!window.confirm('Confirma a rejeição desta dependência?')) return;
    setActionLoading(dep.dependencia_id);
    setActionError('');
    try {
      await api.post(`/dependencias/${dep.dependencia_id}/rejeitar`, { usuario_id: currentUser.id });
      carregarDependencias();
    } catch (err) {
      setActionError(err.response?.data?.error || 'Erro ao rejeitar dependência.');
    } finally {
      setActionLoading(null);
    }
  };

  const handleConcluir = async (dep) => {
    if (!window.confirm('Confirma a conclusão desta dependência sem criar nova demanda?')) return;
    setActionLoading(dep.dependencia_id);
    setActionError('');
    try {
      await api.post(`/dependencias/${dep.dependencia_id}/concluir`, { usuario_id: currentUser.id });
      carregarDependencias();
    } catch (err) {
      setActionError(err.response?.data?.error || 'Erro ao concluir dependência.');
    } finally {
      setActionLoading(null);
    }
  };

  const handleCadastrarFilha = (dep) => {
    navigate(`/nova-demanda?dependencia=${dep.dependencia_id}`);
  };

  if (loading) return <p>Carregando...</p>;

  return (
    <div className="dependencias-page">
      <h2 className="dep-page-title">Dependências por Área</h2>
      <p className="dep-page-subtitle">Demandas que aguardam resposta ou entrega de cada coordenadoria.</p>

      {actionError && (
        <div className="form-error" style={{ marginBottom: '1rem' }}>{actionError}</div>
      )}

      {grupos.length === 0 ? (
        <div className="dep-empty">
          <span>🔗</span>
          <p>Nenhuma dependência de área registrada.</p>
          <p style={{ fontSize: '0.85rem', opacity: 0.6 }}>Ao cadastrar uma demanda, marque as áreas das quais ela depende.</p>
        </div>
      ) : (
        <div className="dep-grupos">
          {grupos.map(grupo => {
            const temPermissao = podeAgir(grupo.coordenadoria_id);
            return (
              <div key={grupo.coordenadoria_id} className="dep-grupo">
                <div className={`dep-grupo-header area-header-${grupo.coordenadoria_id}`}>
                  <span className={`area-dot area-dot-${grupo.coordenadoria_id}`}></span>
                  <h3>Demandas aguardando <strong>{grupo.coordenadoria_nome}</strong></h3>
                  <span className="dep-count">{grupo.demandas.length}</span>
                </div>

                <div className="dep-grupo-list">
                  {[...grupo.demandas].sort((a, b) => (b.pinned ? 1 : 0) - (a.pinned ? 1 : 0)).map(d => {
                    const emAcao = actionLoading === d.dependencia_id;
                    return (
                      <div key={d.dependencia_id} className="dep-card">
                        <div className="dep-card-main">
                          <div className="dep-card-title-row">
                            <div className="dep-card-title-group">
                              {d.pinned && <PinIcon size={13} />}
                              <span className="demand-id-badge">{d.demanda_id}</span>
                              <span className="dep-card-titulo">{d.titulo}</span>
                            </div>
                            <div className="dep-card-badges">
                              <span className={`badge ${PRIORIDADE_LABEL[d.prioridade]?.cls}`}>
                                {PRIORIDADE_LABEL[d.prioridade]?.label || d.prioridade}
                              </span>
                              <span className={`badge ${STATUS_LABEL[d.status]}`}>
                                {d.status}
                              </span>
                            </div>
                          </div>
                          <div className="dep-card-meta">
                            {d.area_origem_nome && (
                              <span className="dep-card-meta-item">
                                <span className="dep-card-meta-label">de</span> {d.area_origem_nome}
                              </span>
                            )}
                            {d.created_at && (
                              <span className="dep-card-meta-item">
                                cadastrada em {formatDateShort(d.created_at)}
                              </span>
                            )}
                          </div>
                          {d.detalhes && (
                            <p className="dep-card-detalhes" title={d.detalhes}>
                              {truncate(d.detalhes)}
                            </p>
                          )}
                        </div>
                        <div className="dep-card-footer">
                          <button
                            className="dep-btn-link"
                            onClick={() => navigate(`/demandas/${d.demanda_id}`)}
                          >
                            Ver detalhes →
                          </button>
                          {temPermissao && (
                            <div className="dep-card-actions">
                              <button
                                className="dep-action-btn dep-action-filha"
                                disabled={emAcao}
                                onClick={() => handleCadastrarFilha(d)}
                              >
                                + Nova demanda filha
                              </button>
                              <button
                                className="dep-action-btn dep-action-concluir"
                                disabled={emAcao}
                                onClick={() => handleConcluir(d)}
                              >
                                Concluir
                              </button>
                              <button
                                className="dep-action-btn dep-action-rejeitar"
                                disabled={emAcao}
                                onClick={() => handleRejeitar(d)}
                              >
                                Rejeitar
                              </button>
                            </div>
                          )}
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
