// frontend/src/app/pages/priorizacoes/priorizacoes.component.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule, DatePipe } from '@angular/common';
import { RouterModule } from '@angular/router';
import { ApiService } from '../../core/services/api.service';
import { UserService } from '../../core/services/user.service';

interface Priorizacao {
  id: number;
  demanda_id: number;
  demanda_titulo: string;
  solicitante_nome: string;
  justificativa: string;
  prioridade_solicitada: string;
  status: string;
  created_at: string;
}

@Component({
  selector: 'app-priorizacoes',
  standalone: true,
  imports: [CommonModule, RouterModule, DatePipe],
  templateUrl: './priorizacoes.component.html',
  providers: [DatePipe]
})
export class PriorizacoesComponent implements OnInit {
  private api = inject(ApiService);
  userService = inject(UserService);

  priorizacoes = signal<Priorizacao[]>([]);
  loading = signal(true);
  error = signal('');
  processing = signal<Set<number>>(new Set());

  ngOnInit(): void {
    this.load();
  }

  load(): void {
    this.loading.set(true);
    this.api.get<Priorizacao[]>('/priorizacoes').subscribe({
      next: (list) => { this.priorizacoes.set(list); this.loading.set(false); },
      error: () => { this.error.set('Erro ao carregar priorizações.'); this.loading.set(false); }
    });
  }

  get pendingPriorizacoes(): Priorizacao[] {
    return this.priorizacoes().filter(p => p.status === 'pendente');
  }

  decidir(p: Priorizacao, aprovado: boolean): void {
    const diretor_id = this.userService.currentUser()?.id;
    this.processing.update(s => { s.add(p.id); return new Set(s); });
    this.api.post<void>(`/priorizacoes/${p.id}/decisao`, { aprovado, diretor_id }).subscribe({
      next: () => { this.processing.update(s => { s.delete(p.id); return new Set(s); }); this.load(); },
      error: () => { this.processing.update(s => { s.delete(p.id); return new Set(s); }); }
    });
  }

  isProcessing(id: number): boolean {
    return this.processing().has(id);
  }

  priorityClass(p: string): string {
    const map: Record<string, string> = {
      'crítica': 'badge-priority-crítica',
      'alta': 'badge-priority-alta',
      'média': 'badge-priority-media',
      'baixa': 'badge-priority-baixa'
    };
    return map[p] ?? '';
  }
}

<div style="max-width:800px;margin:0 auto">
  <h1 class="accent-page-heading" style="margin-bottom:0.5rem">Priorizações</h1>
  <p style="color:var(--text-muted);margin-bottom:2rem">Solicitações de priorização pendentes de aprovação</p>

  <div *ngIf="loading()" style="color:var(--text-muted)">Carregando...</div>
  <div *ngIf="error()" class="form-error">{{ error() }}</div>

  <div *ngIf="!loading() && pendingPriorizacoes.length === 0" style="text-align:center;padding:4rem;color:var(--text-muted)">
    <div style="font-size:2.5rem;margin-bottom:1rem">✅</div>
    Nenhuma solicitação de priorização pendente.
  </div>

  <div class="demand-list">
    <div *ngFor="let p of pendingPriorizacoes" class="demand-card">
      <div class="card-header">
        <div class="card-title">
          <span class="demand-id-badge">{{ p.demanda_id }}</span>
          {{ p.demanda_titulo }}
        </div>
        <div class="card-actions">
          <span *ngIf="p.prioridade_solicitada" class="badge" [class]="priorityClass(p.prioridade_solicitada)">
            → {{ p.prioridade_solicitada }}
          </span>
        </div>
      </div>

      <div class="card-body" style="margin-top:0.25rem">
        <strong>Solicitante:</strong> {{ p.solicitante_nome }}
      </div>

      <div *ngIf="p.justificativa" class="card-body" style="margin-top:0.25rem;font-style:italic">
        "{{ p.justificativa }}"
      </div>

      <div class="card-footer">
        <div class="card-footer-meta">
          <span style="font-size:0.8rem">{{ p.created_at | date:'dd/MM/yyyy HH:mm' }}</span>
        </div>
        <div class="card-footer-actions">
          <a class="btn" style="font-size:0.85rem" [routerLink]="['/demandas', p.demanda_id]">Ver demanda</a>
          <button
            class="btn btn-success"
            [disabled]="isProcessing(p.id)"
            (click)="decidir(p, true)">
            {{ isProcessing(p.id) ? '...' : '✓ Aprovar' }}
          </button>
          <button
            class="btn btn-danger"
            [disabled]="isProcessing(p.id)"
            (click)="decidir(p, false)">
            {{ isProcessing(p.id) ? '...' : '✗ Rejeitar' }}
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

// frontend/src/pages/Priorizacoes.jsx
import React, { useState, useEffect, useContext } from 'react';
import { format } from 'date-fns';
import { useNavigate } from 'react-router-dom';
import api from '../api';
import { UserContext } from '../App';

export default function Priorizacoes() {
  const currentUser = useContext(UserContext);
  const navigate = useNavigate();
  const [demandas, setDemandas] = useState([]);
  const [loading, setLoading] = useState(true);

  const loadData = async () => {
    setLoading(true);
    try {
      const res = await api.get('/priorizacoes');
      setDemandas(res.data);
    } catch (err) {
      console.error(err);
    }
    setLoading(false);
  };

  useEffect(() => {
    loadData();
  }, []);

  const handleDecision = async (id, decisao) => {
    try {
      await api.post(`/priorizacoes/${id}/decisao`, {
        diretor_id: currentUser.id,
        decisao
      });
      loadData();
    } catch (err) {
      console.error(err);
    }
  };

  if (loading) return <p>Carregando pedidos...</p>;

  return (
    <div>
      <h2 className="accent-page-heading" style={{ marginBottom: '2rem' }}>Pedidos de Priorização</h2>
      <div className="demand-list">
        {demandas.length === 0 ? (
          <p style={{ color: 'var(--text-muted)' }}>Nenhum pedido pendente.</p>
        ) : (
          demandas.map(d => (
            <div key={d.id} className={`demand-card area-card-${d.coordenadoria_id}`}>
              <div className="card-header">
                <h3 className="card-title">
                  <span className="demand-id-badge">{d.id}</span> {d.titulo}
                </h3>
              </div>
              <div className="card-body">
                <p style={{ fontWeight: 600, marginBottom: '0.5rem' }}>
                  {d.coordenadoria_nome || 'N/A'}
                </p>
                {d.justificativa_priorizacao && (
                  <div style={{
                    marginTop: '0.75rem',
                    padding: '0.6rem 0.85rem',
                    background: 'rgba(234, 179, 8, 0.08)',
                    borderLeft: '3px solid var(--warning)',
                    borderRadius: '0 4px 4px 0',
                  }}>
                    <p style={{ fontSize: '0.75rem', color: 'var(--warning)', fontWeight: 600, marginBottom: '0.2rem' }}>
                      Justificativa
                    </p>
                    <p style={{ fontSize: '0.85rem', margin: 0 }}>{d.justificativa_priorizacao}</p>
                  </div>
                )}
                <p style={{ marginTop: '0.75rem', fontSize: '0.8rem' }}>
                  <strong>Solicitante:</strong> {d.solicitante || d.criador_nome || 'N/A'}
                  {d.setor_demandante && <> &bull; <strong>Setor Solicitante:</strong> {d.setor_demandante}</>}
                </p>
                <p style={{ fontSize: '0.8rem' }}>
                  <strong>Pedido em:</strong>{' '}
                  {d.priorizacao_solicitada_em
                    ? format(new Date(d.priorizacao_solicitada_em), 'dd/MM/yyyy HH:mm')
                    : format(new Date(d.created_at), 'dd/MM/yyyy HH:mm')}
                </p>
              </div>
              <div className="card-footer" style={{ display: 'flex', justifyContent: 'flex-end', gap: '1rem' }}>
                <button className="btn btn-secondary" onClick={() => navigate(`/demandas/${d.id}`)}>
                  Detalhes
                </button>
                <button className="btn" onClick={() => handleDecision(d.id, 'rejeitado')}>
                  Rejeitar
                </button>
                <button className="btn btn-success" onClick={() => handleDecision(d.id, 'aprovado')}>
                  Aprovar (Fixar)
                </button>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
}
